In [ ]:
!pip install psycopg2-binary
!pip install pandas
!pip install faker

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 94.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting faker
  Downloading faker-40.12.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.12.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 68.3 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.12.0

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="aws-1-ap-northeast-1.pooler.supabase.com",
    database="postgres",
    user="postgres.yaiviopxtnbmpcjxkezp",
    password="Vibhooti@30031994",
    port="6543"
)

cursor = conn.cursor()

print("Connected to Supabase successfully!")

Connected to Supabase successfully!

In [ ]:
cursor.execute("SELECT version();")

print(cursor.fetchone())

('PostgreSQL 17.6 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 15.2.0, 64-bit',)

In [ ]:
##postgresql://postgres.yaiviopxtnbmpcjxkezp:[YOUR-PASSWORD]@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres

In [ ]:
cursor.close()
conn.close()

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS employers (
    employer_id SERIAL PRIMARY KEY,
    company_name VARCHAR(100),
    industry VARCHAR(100),
    location VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
""")

conn.commit()
print("Employers table created")

Employers table created

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS job_seekers (
    seeker_id SERIAL PRIMARY KEY,
    full_name VARCHAR(100),
    email VARCHAR(150) UNIQUE,
    experience_years INT,
    current_location VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
""")

conn.commit()
print("Job seekers table created")

Job seekers table created

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS jobs (
    job_id SERIAL PRIMARY KEY,
    employer_id INT,
    job_title VARCHAR(100),
    location VARCHAR(100),
    salary_min INT,
    salary_max INT,
    posted_date DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (employer_id)
        REFERENCES employers(employer_id)
);
""")

conn.commit()
print("Jobs table created")

Jobs table created

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS applications (
    application_id SERIAL PRIMARY KEY,
    job_id INT,
    seeker_id INT,
    application_date DATE DEFAULT CURRENT_DATE,
    status VARCHAR(50),

    FOREIGN KEY (job_id)
        REFERENCES jobs(job_id),

    FOREIGN KEY (seeker_id)
        REFERENCES job_seekers(seeker_id)
);
""")

conn.commit()
print("Applications table created")

Applications table created

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS skills (
    skill_id SERIAL PRIMARY KEY,
    skill_name VARCHAR(100)
);
""")

conn.commit()

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS job_skills (
    job_id INT,
    skill_id INT,

    FOREIGN KEY (job_id)
        REFERENCES jobs(job_id),

    FOREIGN KEY (skill_id)
        REFERENCES skills(skill_id)
);
""")

conn.commit()

In [ ]:
cursor.execute("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';
""")

for table in cursor.fetchall():
    print(table)

('job_seekers',)
('jobs',)
('employers',)
('applications',)
('skills',)
('job_skills',)

In [ ]:
!pip install faker
!pip install psycopg2-binary
!pip install pandas

Requirement already satisfied: faker in /usr/local/lib/python3.12/dist-packages (40.12.0)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import psycopg2
import random
from faker import Faker
import pandas as pd

ModuleNotFoundError: No module named 'faker'

In [ ]:
conn = psycopg2.connect(
    host="aws-1-ap-northeast-1.pooler.supabase.com",
    database="postgres",
    user="postgres.yaiviopxtnbmpcjxkezp",
    password="Vibhooti@30031994",
    port="6543"
)

cursor = conn.cursor()

fake = Faker()

print("Connected to Supabase")

NameError: name 'Faker' is not defined

In [ ]:
companies = [
"Infosys",
"TCS",
"Accenture",
"Google",
"Amazon",
"Microsoft",
"Wipro",
"Capgemini",
"Deloitte",
"Cognizant"
]

industries = [
"IT",
"Consulting",
"Finance",
"Ecommerce",
"Analytics"
]

locations = [
"Bangalore",
"Hyderabad",
"Pune",
"Mumbai",
"Delhi"
]

employers = []

for i in range(50):
    employers.append((
        random.choice(companies),
        random.choice(industries),
        random.choice(locations)
    ))

employers[:5]

[('Cognizant', 'Analytics', 'Mumbai'),
 ('Capgemini', 'Consulting', 'Hyderabad'),
 ('Accenture', 'Finance', 'Mumbai'),
 ('Deloitte', 'Analytics', 'Mumbai'),
 ('Google', 'Analytics', 'Bangalore')]

In [ ]:
insert_employers = """
INSERT INTO employers (company_name, industry, location)
VALUES (%s,%s,%s)
"""

cursor.executemany(insert_employers, employers)

conn.commit()

print("Employers data inserted")

Employers data inserted

In [ ]:
job_seekers = []

for i in range(200):
    job_seekers.append((
        fake.name(),
        fake.email(),
        random.randint(0,8),
        random.choice(locations)
    ))

job_seekers[:5]

[('Nicole Vasquez', 'egarcia@example.net', 3, 'Hyderabad'),
 ('Bethany Williams', 'vleon@example.com', 1, 'Pune'),
 ('Denise Griffin PhD', 'umorris@example.net', 7, 'Bangalore'),
 ('Rebecca Mccarthy', 'hscott@example.net', 5, 'Pune'),
 ('Martha Potts', 'samanthafowler@example.com', 5, 'Bangalore')]

In [ ]:
insert_seekers = """
INSERT INTO job_seekers
(full_name,email,experience_years,current_location)
VALUES (%s,%s,%s,%s)
"""

cursor.executemany(insert_seekers, job_seekers)

conn.commit()

print("Job seekers inserted")

Job seekers inserted

In [ ]:
job_titles = [
"Data Analyst",
"Business Analyst",
"SQL Developer",
"Data Scientist",
"BI Analyst"
]

jobs = []

for i in range(300):
    jobs.append((
        random.randint(1,50),
        random.choice(job_titles),
        random.choice(locations),
        random.randint(400000,800000),
        random.randint(900000,1500000)
    ))

jobs[:5]

[(4, 'SQL Developer', 'Hyderabad', 466144, 1109347),
 (37, 'BI Analyst', 'Pune', 768295, 910241),
 (35, 'BI Analyst', 'Delhi', 501993, 1083999),
 (26, 'BI Analyst', 'Hyderabad', 693010, 1187770),
 (27, 'Data Scientist', 'Hyderabad', 788025, 1045254)]

In [ ]:
insert_jobs = """
INSERT INTO jobs
(employer_id,job_title,location,salary_min,salary_max)
VALUES (%s,%s,%s,%s,%s)
"""

cursor.executemany(insert_jobs, jobs)

conn.commit()

print("Jobs inserted")

Jobs inserted

In [ ]:
skills_list = [
"SQL",
"Python",
"Power BI",
"Excel",
"Tableau",
"Machine Learning",
"Statistics",
"Data Visualization",
"ETL",
"Communication"
]

for skill in skills_list:
    cursor.execute(
        "INSERT INTO skills (skill_name) VALUES (%s)",
        (skill,)
    )

conn.commit()

print("Skills inserted")

Skills inserted

In [ ]:
job_skills = []

for i in range(600):
    job_skills.append((
        random.randint(1,300),
        random.randint(1,10)
    ))

cursor.executemany(
"""
INSERT INTO job_skills (job_id,skill_id)
VALUES (%s,%s)
""",
job_skills
)

conn.commit()

print("Job skills inserted")

Job skills inserted

In [ ]:
status_list = [
"Applied",
"Shortlisted",
"Interview",
"Rejected",
"Hired"
]

applications = []

for i in range(2000):
    applications.append((
        random.randint(1,300),
        random.randint(1,200),
        random.choice(status_list)
    ))

In [ ]:
cursor.executemany(
"""
INSERT INTO applications
(job_id,seeker_id,status)
VALUES (%s,%s,%s)
""",
applications
)

conn.commit()

print("Applications inserted")

Applications inserted

In [ ]:
cursor.execute("SELECT COUNT(*) FROM job_seekers")
print("Job Seekers:", cursor.fetchone())

cursor.execute("SELECT COUNT(*) FROM employers")
print("Employers:", cursor.fetchone())

cursor.execute("SELECT COUNT(*) FROM jobs")
print("Jobs:", cursor.fetchone())

cursor.execute("SELECT COUNT(*) FROM applications")
print("Applications:", cursor.fetchone())

cursor.execute("SELECT COUNT(*) FROM Job_skills")
print("Job_skills:", cursor.fetchone())

cursor.execute("SELECT COUNT(*) FROM skills")
print("skills:", cursor.fetchone())

Job Seekers: (200,)
Employers: (50,)
Jobs: (300,)
Applications: (2000,)
Job_skills: (600,)
skills: (10,)

In [ ]:
query = """
SELECT
j.job_title,
e.company_name
FROM jobs j
JOIN employers e
ON j.employer_id = e.employer_id
LIMIT 10
"""

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

('SQL Developer', 'Deloitte')
('BI Analyst', 'Cognizant')
('BI Analyst', 'Amazon')
('BI Analyst', 'Capgemini')
('Data Scientist', 'Deloitte')
('BI Analyst', 'Deloitte')
('Data Analyst', 'Amazon')
('Data Scientist', 'Deloitte')
('SQL Developer', 'Capgemini')
('SQL Developer', 'Amazon')

In [ ]:
query = """
SELECT
a.application_id,
js.full_name,
j.job_title,
e.company_name,
a.status
FROM applications a
JOIN job_seekers js
ON a.seeker_id = js.seeker_id
JOIN jobs j
ON a.job_id = j.job_id
JOIN employers e
ON j.employer_id = e.employer_id
LIMIT 15
"""

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

(1, 'Laura Gaines', 'SQL Developer', 'Amazon', 'Hired')
(2, 'Monica Clark', 'Data Analyst', 'Infosys', 'Rejected')
(3, 'Denise Griffin PhD', 'Data Scientist', 'Deloitte', 'Applied')
(4, 'Martha Potts', 'BI Analyst', 'Deloitte', 'Interview')
(5, 'James Ford', 'Business Analyst', 'Amazon', 'Applied')
(6, 'Jennifer Marshall', 'Data Scientist', 'Microsoft', 'Shortlisted')
(7, 'Jason Johnson', 'Business Analyst', 'Google', 'Rejected')
(8, 'Ryan Greene', 'Data Scientist', 'Google', 'Interview')
(9, 'Lauren Cruz', 'Data Analyst', 'Deloitte', 'Applied')
(10, 'Tiffany Moore', 'BI Analyst', 'Amazon', 'Interview')
(11, 'Brent Colon', 'BI Analyst', 'Amazon', 'Rejected')
(12, 'Emily Smith', 'Data Analyst', 'Cognizant', 'Applied')
(13, 'Steven Williams', 'SQL Developer', 'Cognizant', 'Interview')
(14, 'Jessica Madden', 'SQL Developer', 'Cognizant', 'Interview')
(15, 'Nathaniel Curtis', 'SQL Developer', 'Cognizant', 'Shortlisted')

In [ ]:
query = """
WITH company_jobs AS (
    SELECT
    employer_id,
    COUNT(*) AS total_jobs
    FROM jobs
    GROUP BY employer_id
)

SELECT
e.company_name,
cj.total_jobs
FROM company_jobs cj
JOIN employers e
ON cj.employer_id = e.employer_id
ORDER BY total_jobs DESC
LIMIT 10
"""

cursor.execute(query)

print(cursor.fetchall())

[('Capgemini', 13), ('Microsoft', 12), ('Cognizant', 11), ('Cognizant', 10), ('Deloitte', 10), ('Cognizant', 9), ('Amazon', 9), ('Amazon', 8), ('Amazon', 8), ('Deloitte', 8)]

In [ ]:
## Rank highest salary jobs

In [ ]:
query = """
SELECT
job_id,
job_title,
salary_max,
RANK() OVER(ORDER BY salary_max DESC) AS salary_rank
FROM jobs
LIMIT 15
"""

cursor.execute(query)

print(cursor.fetchall())

[(55, 'Business Analyst', 1497319, 1), (297, 'BI Analyst', 1493951, 2), (217, 'BI Analyst', 1493261, 3), (132, 'Data Analyst', 1491403, 4), (259, 'Data Scientist', 1488672, 5), (65, 'BI Analyst', 1485510, 6), (43, 'BI Analyst', 1483638, 7), (113, 'Data Scientist', 1478190, 8), (162, 'Business Analyst', 1477164, 9), (282, 'Data Scientist', 1473466, 10), (84, 'Data Analyst', 1472702, 11), (111, 'SQL Developer', 1470264, 12), (269, 'BI Analyst', 1465393, 13), (134, 'Business Analyst', 1464420, 14), (238, 'SQL Developer', 1463324, 15)]

In [ ]:
cursor.execute("""
CREATE INDEX idx_jobs_location
ON jobs(location);
""")

conn.commit()

print("Index created")

Index created

In [ ]:
cursor.execute("""
CREATE VIEW job_application_summary AS
SELECT
j.job_title,
COUNT(a.application_id) AS total_applications
FROM jobs j
LEFT JOIN applications a
ON j.job_id = a.job_id
GROUP BY j.job_title;
""")

conn.commit()

##Create Materialized View (Advanced)-Materialized views store computed results

In [13]:
cursor.execute("""
CREATE MATERIALIZED VIEW employer_job_stats AS
SELECT
e.company_name,
COUNT(j.job_id) AS total_jobs
FROM employers e
LEFT JOIN jobs j
ON e.employer_id = j.employer_id
GROUP BY e.company_name;
""")

conn.commit()

DuplicateTable: relation "employer_job_stats" already exists

In [14]:
cursor.execute("REFRESH MATERIALIZED VIEW employer_job_stats")

InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

In [4]:
import psycopg2

conn = psycopg2.connect(
    host="aws-1-ap-northeast-1.pooler.supabase.com",
    database="postgres",
    user="postgres.yaiviopxtnbmpcjxkezp",
    password="Vibhooti@30031994",
    port="6543"
)

cursor = conn.cursor()

print("Connected to Supabase successfully!")

Connected to Supabase successfully!

In [ ]:
cursor.execute("SET statement_timeout = 60000;")

Create Trigger (Automation)

Example: Automatically log new applications

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS application_logs (
    log_id SERIAL PRIMARY KEY,
    application_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
""")

conn.commit()

In [ ]:
cursor.execute("""
CREATE OR REPLACE FUNCTION log_new_application()
RETURNS TRIGGER AS $$
BEGIN
INSERT INTO application_logs(application_id)
VALUES (NEW.application_id);

RETURN NEW;
END;
$$ LANGUAGE plpgsql;
""")

In [ ]:
cursor.execute("""
CREATE TRIGGER application_insert_trigger
AFTER INSERT ON applications
FOR EACH ROW
EXECUTE FUNCTION log_new_application();
""")

conn.commit()

Stored Procedure

Example: Insert a new job

In [ ]:
cursor.execute("""
CREATE OR REPLACE PROCEDURE add_job(
emp_id INT,
title VARCHAR,
location VARCHAR,
salary1 INT,
salary2 INT
)
LANGUAGE plpgsql
AS $$
BEGIN
INSERT INTO jobs(employer_id,job_title,location,salary_min,salary_max)
VALUES(emp_id,title,location,salary1,salary2);
END;
$$
""")

conn.commit()

In [ ]:
cursor.execute("CALL add_job(1,'Senior Data Analyst','Bangalore',900000,1500000)")
conn.commit()

DML Operations- INSERT, UPDATE, Delete

In [ ]:
cursor.execute("""
INSERT INTO skills(skill_name)
VALUES ('Deep Learning')
""")

conn.commit()

In [ ]:
cursor.execute("""
UPDATE jobs
SET salary_max = salary_max + 50000
WHERE job_title='Data Analyst'
""")

conn.commit()

In [ ]:
cursor.execute("""
DELETE FROM skills
WHERE skill_name='Deep Learning'
""")

conn.commit()

Transaction Management in Google Colab
Transaction Flow:

Start Transaction
      ↓
Execute Queries
      ↓
Commit  (save changes permanently)
or
Rollback (undo changes)

In [ ]:
##COMMIT saves the changes permanently in the database.Example: Insert a new job and commit.

In [ ]:
cursor.execute("""
INSERT INTO jobs (employer_id,job_title,location,salary_min,salary_max)
VALUES (2,'Junior Data Analyst','Hyderabad',500000,800000)
""")

conn.commit()

print("Transaction committed successfully")

Transaction committed successfully

In [ ]:
##ROLLBACK (Undo Transaction)-If something goes wrong, we undo changes using rollback.

In [ ]:
try:

    cursor.execute("""
    INSERT INTO skills(skill_name)
    VALUES ('Big Data')
    """)

    cursor.execute("""
    INSERT INTO skills(skill_name)
    VALUES ('Big Data')
    """)

    conn.commit()

except Exception as e:

    conn.rollback()

    print("Error occurred, transaction rolled back")

Explanation:

First insert → success
Second insert → error (duplicate)
Rollback → both inserts cancelled

This prevents bad data from entering the database.

In [ ]:
##SAVEPOINT (Partial Rollback)-Sometimes we want to rollback only part of the transaction.

In [ ]:
cursor.execute("BEGIN")

cursor.execute("""
INSERT INTO skills(skill_name)
VALUES ('Cloud Computing')
""")

cursor.execute("SAVEPOINT before_error")

try:

    cursor.execute("""
    INSERT INTO skills(skill_name)
    VALUES ('Cloud Computing')
    """)

except:

    cursor.execute("ROLLBACK TO SAVEPOINT before_error")

conn.commit()

print("Savepoint example completed")

Savepoint example completed

Insert 1 → success
SAVEPOINT created
Insert 2 → error
Rollback to savepoint
First insert remains
Second insert cancelled

In [ ]:
try:

    cursor.execute("BEGIN")

    cursor.execute("""
    INSERT INTO applications(job_id,seeker_id,status)
    VALUES (10,20,'Applied')
    """)

    cursor.execute("""
    UPDATE jobs
    SET salary_max = salary_max + 10000
    WHERE job_id = 10
    """)

    conn.commit()

    print("Application transaction completed")

except:

    conn.rollback()

    print("Transaction failed and rolled back")

Application transaction completed

In [ ]:
cursor.execute("""
SELECT * FROM applications
ORDER BY application_id DESC
LIMIT 5
""")

print(cursor.fetchall())

[(2001, 10, 20, datetime.date(2026, 4, 4), 'Applied'), (2000, 44, 187, datetime.date(2026, 4, 2), 'Hired'), (1999, 300, 195, datetime.date(2026, 4, 2), 'Hired'), (1998, 147, 186, datetime.date(2026, 4, 2), 'Applied'), (1997, 257, 104, datetime.date(2026, 4, 2), 'Rejected')]

Data Manipulation with Pandas (Preparing Data for Power BI).

In [1]:
import pandas as pd
import psycopg2

conn = psycopg2.connect(
    host="aws-1-ap-northeast-1.pooler.supabase.com",
    database="postgres",
    user="postgres.yaiviopxtnbmpcjxkezp",
    password="Vibhooti@30031994",
    port="6543"
)

print("Connected to database")

Connected to database

In [ ]:
jobs_df = pd.read_sql("SELECT * FROM jobs", conn)

jobs_df.head()

/tmp/ipykernel_23459/1006490612.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  jobs_df = pd.read_sql("SELECT * FROM jobs", conn)

,job_id,employer_id,job_title,location,salary_min,salary_max,posted_date
0,1,4,SQL Developer,Hyderabad,466144,1109347,2026-04-02
1,2,37,BI Analyst,Pune,768295,910241,2026-04-02
2,3,35,BI Analyst,Delhi,501993,1083999,2026-04-02
3,4,26,BI Analyst,Hyderabad,693010,1187770,2026-04-02
4,5,27,Data Scientist,Hyderabad,788025,1045254,2026-04-02

In [ ]:
applications_df = pd.read_sql("SELECT * FROM applications", conn)

applications_df.head()

/tmp/ipykernel_23459/1985042380.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  applications_df = pd.read_sql("SELECT * FROM applications", conn)

   application_id  job_id  seeker_id application_date     status
0               1      91        129       2026-04-02      Hired
1               2     186        101       2026-04-02   Rejected
2               3     296          3       2026-04-02    Applied
3               4       6          5       2026-04-02  Interview
4               5      76         31       2026-04-02    Applied

In [ ]:
seekers_df = pd.read_sql("SELECT * FROM job_seekers", conn)

seekers_df.head()

/tmp/ipykernel_23459/2506926808.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  seekers_df = pd.read_sql("SELECT * FROM job_seekers", conn)

,seeker_id,full_name,email,experience_years,current_location,created_at
0,1,Nicole Vasquez,egarcia@example.net,3,Hyderabad,2026-04-02 11:50:19.383152
1,2,Bethany Williams,vleon@example.com,1,Pune,2026-04-02 11:50:19.383152
2,3,Denise Griffin PhD,umorris@example.net,7,Bangalore,2026-04-02 11:50:19.383152
3,4,Rebecca Mccarthy,hscott@example.net,5,Pune,2026-04-02 11:50:19.383152
4,5,Martha Potts,samanthafowler@example.com,5,Bangalore,2026-04-02 11:50:19.383152

In [ ]:
jobs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   job_id       302 non-null    int64
 1   employer_id  302 non-null    int64
 2   job_title    302 non-null    object
 3   location     302 non-null    object
 4   salary_min   302 non-null    int64
 5   salary_max   302 non-null    int64
 6   posted_date  302 non-null    object
dtypes: int64(4), object(3)
memory usage: 16.6+ KB

In [ ]:
jobs_df.isnull().sum()

job_id         0
employer_id    0
job_title      0
location       0
salary_min     0
salary_max     0
posted_date    0
dtype: int64

In [ ]:
jobs_df["salary_range"] = jobs_df["salary_max"] - jobs_df["salary_min"]

jobs_df.head()

,job_id,employer_id,job_title,location,salary_min,salary_max,posted_date,salary_range,avg_salary
0,1,4,SQL Developer,Hyderabad,466144,1109347,2026-04-02,643203,787745.5
1,2,37,BI Analyst,Pune,768295,910241,2026-04-02,141946,839268.0
2,3,35,BI Analyst,Delhi,501993,1083999,2026-04-02,582006,792996.0
3,4,26,BI Analyst,Hyderabad,693010,1187770,2026-04-02,494760,940390.0
4,5,27,Data Scientist,Hyderabad,788025,1045254,2026-04-02,257229,916639.5

In [ ]:
jobs_df["avg_salary"] = (jobs_df["salary_min"] + jobs_df["salary_max"]) / 2
jobs_df.head()

,job_id,employer_id,job_title,location,salary_min,salary_max,posted_date,salary_range,avg_salary
0,1,4,SQL Developer,Hyderabad,466144,1109347,2026-04-02,643203,787745.5
1,2,37,BI Analyst,Pune,768295,910241,2026-04-02,141946,839268.0
2,3,35,BI Analyst,Delhi,501993,1083999,2026-04-02,582006,792996.0
3,4,26,BI Analyst,Hyderabad,693010,1187770,2026-04-02,494760,940390.0
4,5,27,Data Scientist,Hyderabad,788025,1045254,2026-04-02,257229,916639.5

Aggregation Analysis

In [ ]:
##Average salary by job title

In [ ]:
salary_analysis = jobs_df.groupby("job_title")["avg_salary"].mean()

salary_analysis

job_title
BI Analyst             8.968241e+05
Business Analyst       8.813972e+05
Data Analyst           9.126166e+05
Data Scientist         9.095240e+05
Junior Data Analyst    6.500000e+05
SQL Developer          8.848570e+05
Senior Data Analyst    1.200000e+06
Name: avg_salary, dtype: float64

In [ ]:
##Total jobs by location

In [ ]:
location_jobs = jobs_df.groupby("location")["job_id"].count()

location_jobs

location
Bangalore    57
Delhi        54
Hyderabad    57
Mumbai       69
Pune         65
Name: job_id, dtype: int64

Merge Tables (Like SQL JOIN)

In [ ]:
##Combine applications + jobs

In [ ]:
merged_df = pd.merge(
    applications_df,
    jobs_df,
    on="job_id",
    how="left"
)

merged_df.head()

,application_id,job_id,seeker_id,application_date,status,employer_id,job_title,location,salary_min,salary_max,posted_date,salary_range,avg_salary
0,1,91,129,2026-04-02,Hired,49,SQL Developer,Mumbai,523968,1046928,2026-04-02,522960,785448.0
1,2,186,101,2026-04-02,Rejected,7,Data Analyst,Bangalore,731311,1495227,2026-04-02,763916,1113269.0
2,3,296,3,2026-04-02,Applied,27,Data Scientist,Hyderabad,777098,1375128,2026-04-02,598030,1076113.0
3,4,6,5,2026-04-02,Interview,12,BI Analyst,Mumbai,480261,1300706,2026-04-02,820445,890483.5
4,5,76,31,2026-04-02,Applied,40,Business Analyst,Hyderabad,565904,1184223,2026-04-02,618319,875063.5

In [ ]:
##add job_seekar

In [ ]:
final_df = pd.merge(
    merged_df,
    seekers_df,
    on="seeker_id",
    how="left"
)

final_df.head()

,application_id,job_id,seeker_id,application_date,status,employer_id,job_title,location,salary_min,salary_max,posted_date,salary_range,avg_salary,full_name,email,experience_years,current_location,created_at
0,1,91,129,2026-04-02,Hired,49,SQL Developer,Mumbai,523968,1046928,2026-04-02,522960,785448.0,Laura Gaines,donna33@example.net,8,Delhi,2026-04-02 11:50:19.383152
1,2,186,101,2026-04-02,Rejected,7,Data Analyst,Bangalore,731311,1495227,2026-04-02,763916,1113269.0,Monica Clark,dwilliams@example.com,3,Hyderabad,2026-04-02 11:50:19.383152
2,3,296,3,2026-04-02,Applied,27,Data Scientist,Hyderabad,777098,1375128,2026-04-02,598030,1076113.0,Denise Griffin PhD,umorris@example.net,7,Bangalore,2026-04-02 11:50:19.383152
3,4,6,5,2026-04-02,Interview,12,BI Analyst,Mumbai,480261,1300706,2026-04-02,820445,890483.5,Martha Potts,samanthafowler@example.com,5,Bangalore,2026-04-02 11:50:19.383152
4,5,76,31,2026-04-02,Applied,40,Business Analyst,Hyderabad,565904,1184223,2026-04-02,618319,875063.5,James Ford,hblackwell@example.org,8,Pune,2026-04-02 11:50:19.383152

Application Status Analysis

In [ ]:
##value_counts() counts how many times each unique value appears in a column

In [ ]:
status_counts = final_df["status"].value_counts()

status_counts

status
Interview      419
Applied        407
Rejected       404
Shortlisted    389
Hired          382
Name: count, dtype: int64

In [ ]:
##Applications per job- 'count()' counts the number of non-null (not NaN) values in a column or DataFrame

In [ ]:
apps_per_job = final_df.groupby("job_title")["application_id"].count()

apps_per_job

job_title
BI Analyst          363
Business Analyst    422
Data Analyst        406
Data Scientist      395
SQL Developer       415
Name: application_id, dtype: int64

Export Dataset for Power BI

In [ ]:
##create a clean dataset

In [ ]:
analytics_df = final_df[
[
"job_title",
"location",
"salary_min",
"salary_max",
"status",
"experience_years"
]
]
analytics_df.head()

,job_title,location,salary_min,salary_max,status,experience_years
0,SQL Developer,Mumbai,523968,1046928,Hired,8
1,Data Analyst,Bangalore,731311,1495227,Rejected,3
2,Data Scientist,Hyderabad,777098,1375128,Applied,7
3,BI Analyst,Mumbai,480261,1300706,Interview,5
4,Business Analyst,Hyderabad,565904,1184223,Applied,8

In [ ]:
##export csv

In [ ]:
analytics_df.to_csv("job_portal_dataset.csv", index=False)

In [ ]:
##download file

In [ ]:
from google.colab import files
files.download("job_portal_dataset.csv")

Step 7 -Create M Views → Extract → CSV → Power BI

In [18]:
cursor.execute("""
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_job_analytics AS
SELECT
    a.application_id,
    a.application_date,

    j.job_id,
    j.job_title,
    j.location,
    j.salary_min,
    j.salary_max,
    (j.salary_min + j.salary_max)/2 AS avg_salary,

    e.company_name,
    e.industry,

    js.seeker_id,
    js.experience_years,
    js.current_location,

    a.status

FROM applications a
JOIN jobs j ON a.job_id = j.job_id
JOIN employers e ON j.employer_id = e.employer_id
JOIN job_seekers js ON a.seeker_id = js.seeker_id;
""")

conn.commit()

InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

In [19]:
conn.rollback()

In [6]:
cursor.execute("""
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_job_analytics AS
SELECT
    a.application_id,
    a.application_date,

    j.job_id,
    j.job_title,
    j.location,
    j.salary_min,
    j.salary_max,
    (j.salary_min + j.salary_max)/2 AS avg_salary,

    e.company_name,
    e.industry,

    js.seeker_id,
    js.experience_years,
    js.current_location,

    a.status

FROM applications a
JOIN jobs j ON a.job_id = j.job_id
JOIN employers e ON j.employer_id = e.employer_id
JOIN job_seekers js ON a.seeker_id = js.seeker_id;
""")

conn.commit()

In [7]:
cursor.execute("REFRESH MATERIALIZED VIEW mv_job_analytics")
conn.commit()

Extract in Colab

In [8]:
import pandas as pd

df = pd.read_sql("SELECT * FROM mv_job_analytics", conn)

df.head()

/tmp/ipykernel_4944/4207871828.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM mv_job_analytics", conn)

,application_id,application_date,job_id,job_title,location,salary_min,salary_max,avg_salary,company_name,industry,seeker_id,experience_years,current_location,status
0,1,2026-04-02,91,SQL Developer,Mumbai,523968,1046928,785448,Amazon,IT,129,8,Delhi,Hired
1,2,2026-04-02,186,Data Analyst,Bangalore,731311,1495227,1113269,Infosys,Ecommerce,101,3,Hyderabad,Rejected
2,3,2026-04-02,296,Data Scientist,Hyderabad,777098,1375128,1076113,Deloitte,Consulting,3,7,Bangalore,Applied
3,4,2026-04-02,6,BI Analyst,Mumbai,480261,1300706,890483,Deloitte,IT,5,5,Bangalore,Interview
4,5,2026-04-02,76,Business Analyst,Hyderabad,565904,1184223,875063,Amazon,IT,31,8,Pune,Applied

In [ ]:
##Export to CSV

In [9]:
df.to_csv("job_analytics.csv", index=False)

from google.colab import files
files.download("job_analytics.csv")